#!/bin/sh

USER="takumi"
GECOS="Takumi Takahashi"
PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB/qb8XxUTnQQgEYF3W2ZaVu8VWqzoYNxpKA/FOFDhoG takumi"

########################################################################################################################
# init
########################################################################################################################

mkdir -p /dev
mkdir -p /etc/dropbear
mkdir -p /home
mkdir -p /proc
mkdir -p /root
mkdir -p /run
mkdir -p /sys
mkdir -p /var/log

mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts   devpts   /dev/pts
mount -t proc     proc     /proc
mount -t sysfs    sysfs    /sys

########################################################################################################################
# cmdline
########################################################################################################################

# shellcheck disable=SC2013
for x in $(cat /proc/cmdline); do
  case $x in
    root=*)
      ROOT=${x#root=}
      ;;
  esac
done

########################################################################################################################
# root
########################################################################################################################

echo "root:x:0:" > /etc/group
echo "root:x:0:0:root:/root:/bin/sh" > /etc/passwd
echo "root:root" | chpasswd 2> /dev/null

########################################################################################################################
# user
########################################################################################################################

addgroup -g 1000 "${USER}"
adduser -u 1000 -G "${USER}" -s /bin/sh -h "/home/${USER}" -D "${USER}"
echo "${USER}:${USER}" | chpasswd 2> /dev/null

mkdir -m 0700 "/home/${USER}/.ssh"
echo "${PUBKEY}" > "/home/${USER}/.ssh/authorized_keys"
chown -R 1000:1000 "/home/${USER}"

chmod u+s /bin/su

########################################################################################################################
# network
########################################################################################################################

ifconfig eth0 up
ip addr add 192.168.100.90/24 dev eth0
echo "nameserver 192.168.100.100" > /etc/resolv.conf

########################################################################################################################
# dropbear
########################################################################################################################

dropbear -R -E -P /run/dropbear.pid -w -j -k

########################################################################################################################
# rootfs
########################################################################################################################

mkdir -p /live
mount -t tmpfs tmpfs /live

mkdir -p /live/rootfs /live/modules /live/upper /live/work
wget -P /live http://boot.internal/rpi/boot/rootfs.squashfs
mount -t squashfs /live/rootfs.squashfs /live/rootfs

mkdir -p /live/modules/usr/lib
cp -r /lib/modules /live/modules/usr/lib/modules

mkdir -p /newroot
mount -t overlay -o lowerdir=/live/rootfs:/live/modules,upperdir=/live/upper,workdir=/live/work overlay /newroot

mkdir -p /newroot/run
mount -t tmpfs -o mode=755,nodev,nosuid,strictatime tmpfs /newroot/run

mkdir -p /newroot/run/live
mount --move /live /newroot/run/live

########################################################################################################################
# config
########################################################################################################################

mkdir -p /newroot/run/systemd/network

cat > /newroot/run/systemd/network/00-default.network <<- __EOF__
[Match]
Name=*
!Name=veth*
Type=ether

[Network]
LinkLocalAddressing=yes
IPv6LinkLocalAddressGenerationMode=stable-privacy
DHCP=yes
LLDP=yes

[DHCPv4]
ClientIdentifier=mac
__EOF__

mkdir -p /newroot/run/systemd/system

cat > /newroot/run/systemd/system/admin-user.service <<- __EOF__
[Unit]
Description=Admin User for ${USER}

[Service]
Type=oneshot
ExecStart=/sbin/adduser --disabled-password --shell /bin/bash --home "/home/${USER}" --gecos "${GECOS}" "${USER}"
ExecStart=/sbin/adduser "${USER}" adm
ExecStart=/sbin/adduser "${USER}" sudo
ExecStart=/sbin/adduser "${USER}" staff
ExecStart=/sbin/adduser "${USER}" users
ExecStart=/bin/sh -c '/bin/echo "${USER}:${USER}" | /sbin/chpasswd'
ExecStart=/bin/mkdir -m 0700 "/home/${USER}/.ssh"
ExecStart=/bin/sh -c '/bin/echo "${PUBKEY}" > "/home/${USER}/.ssh/authorized_keys"'
ExecStart=/bin/chown -R "${USER}:${USER}" "/home/${USER}"
ExecStart=/bin/sh -c '/bin/echo "%%sudo ALL=(ALL:ALL) NOPASSWD: ALL" > "/etc/sudoers.d/no_passwd"'

[Install]
WantedBy=multi-user.target
__EOF__

mkdir -p /live/upper/etc/systemd/system
ln -s /run/systemd/system/admin-user.service /live/upper/etc/systemd/system/admin-user.service

########################################################################################################################
# exec
########################################################################################################################

if echo "${ROOT:-}" | grep -Eqs '^/dev/ram'; then
  exec /bin/sh
else
  kill -KILL "$(cat /run/dropbear.pid)"

  ip addr del 192.168.100.90/24 dev eth0
  ifconfig eth0 down

  umount /sys
  umount /proc
  umount /dev/pts
  umount /dev

  exec /sbin/switch_root /newroot /sbin/init
fi
